### ISSUE TITLE
FSP Wiki Setup + Feature List + Schema

### ISSUE THREAD

**Issue by mwmadsen67** [mmoses1127/Bravo#1]
Hi Michael, here is a checklist for going through tonight's homework and setting up your wiki. If it makes it easier for you, you can check these off while working through it, otherwise I will check them off when I review your docs tomorrow.

---

# Wiki Page Home

- [x] Is the first page you see upon entering the wiki
- [x] Contains a welcome message
- [x] Contains a link/placeholder for a link to the live page
- [x] All links in the right sidebar should contain each wiki page and link to the correct page
- [x] Correctly formatted
    - [x] each wiki page is listed in bullet points
    - [x] all links route the correct page

---

# Feature List

- [x] Should have 7 Features.
    - [x] 3 of those are User Auth, Render.io, and Production README.
    - [x] The other 4 are from the [Feature List for approved apps](https://open.appacademy.io/learn/ch---aug-2022-sf-cohort/react/approved-full-stack-projects) or they have clarified them with you
- [x] Contains a description sentence of the app
- [x] Includes two to three detailed bullets on functionality and presentation of feature
- [x] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [x] Estimates how long it will take the code each feature
- [x] Correctly formatted
    - [x] features are listed in an ordered list
    - [x] Each feature is broken down into bullet points

---

# Database Schema

- [x] Contains correct datatypes
- [x] Contains appropriate constraints/details
    - [x] primary key
    - [x] not null
    - [x] unique
    - [x] indexed
    - [x] foreign key
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
  - [x] foreign key and table name are lowercased, snake_cased and `back_ticked`
- [x] Correctly formatted
    - [x] schema is written in a table format
    - [x] the table's name are lowercased, snake_cased and `back_ticked`
    - [x] the table header column names are bolded
    - [x] columns names are lowercased and snaked_cased and `back_ticked`

---

**Comment by mmoses1127** [comment]
fleshed out wiki structure; completed feature list and schema

**Comment by mwmadsen67** [comment]
Great work so far, here are some of my notes after going through this.

For your feature list, I think its all good except I would include the training calendar as another bonus feature, since rides, follows, comments, and kudos is 4 features.

Here are some notes on the schema:
- I don't think you should have a unique constraint on username. A unique email is good enough for user auth and some people have the same names.
- Rides is looking pretty good, you can check my comment on the other issue you made to see what I think of GPS data. For pictures, you don't need to include a column, this will be covered by active storage.
- A bunch of your tables say `index on id, unique: true` this is unnecessary to point out.
- The combination of follower_id and followee_id should be unique true, since you can only follow someone once.
- same thing for kudos
- your comments table is missing a column for the body of the comment

If you get to bonus features we can go through those tables together. For now, I hope this feedback is helpful! Nice work so far!
